apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kube-system
stringData:
  key_id: "QUtJQVJSQVhMUkRHNEtETEJDNzU="
  access_key: "aldNcEJuTHo2WmtzaWFwRi9RK2Urd0NOV1NNQXovUEJFaXBGSG40Zg=="