apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kube-system
stringData:
  key_id: "QUtJQVdMRUVMSTVRUjVaNVRXTUk="
  access_key: "MjhBTjludGMwL2liQ2cvSVU1SkhVQVNQa2pUbkZ2Nk8rUytadGQxdw=="